<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Last Name</name>
   <tag></tag>
   <elementGuidId>dea9fc86-5599-4f5f-aa90-77307fb903ea</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//*[@name = 'lastName']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>[name=&quot;lastName&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:attr=[placeholder=&quot;Last Name&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>db144a39-c758-4d0e-94cf-102d5b62a3e4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>slds-input</value>
      <webElementGuid>912c2a20-d219-43b4-8e21-6b9af5812e81</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>part</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>d9fb881c-11d2-47a7-b5b7-3213d10fca2d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>input-1054</value>
      <webElementGuid>adcc51be-5d3f-408b-b6ae-194b8f368d0f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>80</value>
      <webElementGuid>1c2c14c3-494e-4964-8a99-4f82198f8c32</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>lastName</value>
      <webElementGuid>30cc6808-42bd-433a-b767-a2ddf5983863</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Last Name</value>
      <webElementGuid>796980ae-a419-4228-9a0c-7e1a29543f46</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>7a5968e0-af83-4927-a37c-c7c968343d6c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-describedby</name>
      <type>Main</type>
      <value>help-message-1054</value>
      <webElementGuid>0adfe5d7-4964-43d1-9692-cb05075d9131</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parent</name>
      <type>Main</type>
      <value>md5.v1-34db83ca39718938dfe83191c0210b6b</value>
      <webElementGuid>03f4f007-0238-41d2-bbd5-86f32ccc1e70</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@name = 'lastName']</value>
      <webElementGuid>57ad0f3e-1711-4bf3-a4a6-3a9c324d40ae</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//*[@name = 'lastName']</value>
      <webElementGuid>c8e71556-7dbb-4011-b6ba-fa6cfb63e1ce</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'input-1054' and @name = 'lastName' and @placeholder = 'Last Name' and @type = 'text']</value>
      <webElementGuid>972d6483-a2e3-4b73-bb3d-219bd9c52266</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
