<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_New</name>
   <tag></tag>
   <elementGuidId>41252906-350b-45eb-9f40-03f57304db50</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@title = 'New']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div[title=&quot;New&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=button[name=&quot;New&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>5a2a5996-6fa1-46ca-8060-ec9bc751eafd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>New</value>
      <webElementGuid>37e068d4-2904-40b3-9330-a6124a60128f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-aura-rendered-by</name>
      <type>Main</type>
      <value>2648:0</value>
      <webElementGuid>6e9821fc-8a7a-4d40-8e83-48fb6c30ce03</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>New</value>
      <webElementGuid>e32cd090-ef98-4e83-9258-0bbc8b3ab6ab</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parent</name>
      <type>Main</type>
      <value>md5.v1-a85f250787da73045f2752c4fa2cb1e9</value>
      <webElementGuid>2060670f-93e7-439e-a16f-e043a44eb170</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//div[@title = 'New']</value>
      <webElementGuid>81c1b6a8-fcde-4fe8-9a6d-fa2632ceb52a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@title = 'New']</value>
      <webElementGuid>88af0d93-1971-42ed-b8d1-5766b8e8e71f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@title = 'New' and (text() = 'New' or . = 'New')]</value>
      <webElementGuid>a0e083f9-12bb-4497-b80a-cfd9deb2829f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
