<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>getLeadName</name>
   <tag></tag>
   <elementGuidId>01a5e940-c89b-4949-a87e-9b10fac57e6d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//tr[1]//th[1]//a</value>
      </entry>
      <entry>
         <key>CSS</key>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=link[name=&quot;test 1770385736&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>e00a2ab9-f8cc-4271-abe5-0d70b6c002b8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-refid</name>
      <type>Main</type>
      <value>recordId</value>
      <webElementGuid>f193c092-7f61-4e8e-b5bc-389d15b97b63</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-special-link</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>6c6e2f6e-a1c5-4f2b-839c-508acacc7c98</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>test 1770385736</value>
      <webElementGuid>0278ab6b-8d46-4118-a10a-76819bff0351</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-navigable</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>2d764ec9-f2ef-40ca-b78d-82a7d86b4485</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>target</name>
      <type>Main</type>
      <value>_blank</value>
      <webElementGuid>cab7c5e0-a721-42db-91ee-3ea07fc49fd2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-ownerid</name>
      <type>Main</type>
      <value>726:0</value>
      <webElementGuid>28f47e64-9fe4-4da2-8afa-81ffa9a683e9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-recordid</name>
      <type>Main</type>
      <value>003dN00000KgA13QAF</value>
      <webElementGuid>e8189a8b-a065-42e3-a2eb-f947455a50b0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>rel</name>
      <type>Main</type>
      <value>noreferrer</value>
      <webElementGuid>24ab2429-76f2-4e70-99c4-59541d61b0ba</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/lightning/r/003dN00000KgA13QAF/view</value>
      <webElementGuid>2d77dd2a-6844-48a4-9cf5-01116ff89a6b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>slds-truncate outputLookupLink slds-truncate outputLookupLink-003dN00000KgA13QAF-726:0 forceOutputLookup</value>
      <webElementGuid>e5fc856e-eb30-4bba-970d-67ba54239841</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-aura-rendered-by</name>
      <type>Main</type>
      <value>737:0</value>
      <webElementGuid>28bc447c-a7ef-4bde-b299-e4d4e589a688</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-aura-class</name>
      <type>Main</type>
      <value>forceOutputLookup</value>
      <webElementGuid>b034669d-5cf4-4f51-bbf4-def6b78c7291</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>test 1770385736</value>
      <webElementGuid>a2ed457b-396c-49cf-a197-6d1d9280d019</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;brandBand_1&quot;)/div[@class=&quot;slds-template__container&quot;]/div[@class=&quot;windowViewMode-maximized oneContent active lafPageHost&quot;]/div[@class=&quot;oneConsoleObjectHome runtime_sales_easyObjectHomeDesktop&quot;]/div[@class=&quot;test-listViewManager slds-card slds-card_boundary slds-grid slds-grid_vertical slds-grid--vertical forceListViewManager&quot;]/div[@class=&quot;slds-grid listDisplays safari-workaround-anchor&quot;]/div[@class=&quot;slds-grid listViewContainer safari-workaround&quot;]/div[@class=&quot;slds-col slds-no-space forceListViewManagerPrimaryDisplayManager&quot;]/div[@class=&quot;undefined forceListViewManagerGrid&quot;]/div[@class=&quot;listViewContent slds-table--header-fixed_container slds-table_header-fixed_container&quot;]/div[@class=&quot;uiScroller scroller-wrapper scroll-bidirectional native&quot;]/div[@class=&quot;scroller actionBarPlugin&quot;]/div[@class=&quot;slds-table_edit_container slds-table--edit_container slds-is-relative  inlineEdit--enabled keyboardMode--active inlineEditGrid forceInlineEditGrid&quot;]/table[@class=&quot;slds-table forceRecordLayout slds-table_header-fixed slds-table--header-fixed slds-table_edit slds-table--edit slds-table_bordered slds-table--bordered resizable-cols slds-table--resizable-cols uiVirtualDataTable&quot;]/tbody[1]/tr[1]/th[@class=&quot;slds-cell-edit lockTrigger cellContainer&quot;]/span[@class=&quot;slds-grid slds-grid_align-spread slds-grid--align-spread forceInlineEditCell&quot;]/a[@class=&quot;slds-truncate outputLookupLink slds-truncate outputLookupLink-003dN00000KgA13QAF-726:0 forceOutputLookup&quot;]</value>
      <webElementGuid>dbadca48-1d45-46c6-9f23-fce059b65cea</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='brandBand_1']/div/div/div/div/div[2]/div/div/div[2]/div[2]/div/div/div/table/tbody/tr/th/span/a</value>
      <webElementGuid>95a11109-62ae-4946-8a9c-d6eb40d03097</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'test 1770385736')]</value>
      <webElementGuid>a6eec8a8-f7f5-4a52-81df-03cbc8e8133a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Action'])[1]/following::a[1]</value>
      <webElementGuid>3d46aef7-c459-42ef-878f-c93769f47ee7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Show Contact Owner Alias Column Actions'])[1]/following::a[1]</value>
      <webElementGuid>2a750197-2120-4069-8559-9dd48920119a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Locked Name: Item test 1770385736'])[1]/preceding::a[1]</value>
      <webElementGuid>86fb5fe8-b6ca-49dc-9e13-acfaa9aeb3b8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='User_1770355022101'])[1]/preceding::a[1]</value>
      <webElementGuid>cacbd66a-f984-4c91-b141-b4fe56c529dc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='test 1770385736']/parent::*</value>
      <webElementGuid>65b86f6d-3390-4278-8d8f-e1b7172ec522</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/lightning/r/003dN00000KgA13QAF/view')]</value>
      <webElementGuid>dffa556f-369a-4a55-9d83-86c1bbd7b4e8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//th/span/a</value>
      <webElementGuid>d33472b5-1b1d-4c1a-b4fa-6fcbbc13f89c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@title = 'test 1770385736' and @href = '/lightning/r/003dN00000KgA13QAF/view' and (text() = 'test 1770385736' or . = 'test 1770385736')]</value>
      <webElementGuid>0cae8da4-4cb4-40b0-8aef-e9bec65e273f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
