<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>textarea_Description</name>
   <tag></tag>
   <elementGuidId>36906016-da91-4c91-a9a2-37f6c294fc4a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>[lwc-15ihn5f4djl=&quot;&quot;] .slds-textarea</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//label[text()='Description']//following::textarea[1]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;Description&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>textarea</value>
      <webElementGuid>bb3fb26b-8287-4937-b24d-1500bbbb26a7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>part</name>
      <type>Main</type>
      <value>textarea</value>
      <webElementGuid>5e620f2f-b48b-426e-9818-b98d754b91e6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>input-284</value>
      <webElementGuid>2d116301-fd87-42fa-b76e-e3d420ac99d7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>32000</value>
      <webElementGuid>0df6fb75-8513-4ad0-b3a1-30679e2edb63</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>slds-textarea</value>
      <webElementGuid>e46a1a4a-45bb-4c22-aea9-579130d0ebef</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parent</name>
      <type>Main</type>
      <value>md5.v1-4dbcf98f0d015cc332fc86215605ac80</value>
      <webElementGuid>800d09d1-0f69-4996-92c5-762400fb4124</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@lwc-15ihn5f4djl = '']//*[@class and contains(concat(' ', normalize-space(@class), ' '), ' slds-textarea ')]</value>
      <webElementGuid>a7afd35a-a069-4ee8-98cc-afaf86696871</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//*[@lwc-15ihn5f4djl = '']//*[@class and contains(concat(' ', normalize-space(@class), ' '), ' slds-textarea ')]</value>
      <webElementGuid>7c652aac-8abd-491a-b367-6af20cc605ef</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//textarea[@id = 'input-284']</value>
      <webElementGuid>01a49a4c-3267-4ecb-aa08-b8b70dfea8ab</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
