<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>textarea_Description</name>
   <tag></tag>
   <elementGuidId>36906016-da91-4c91-a9a2-37f6c294fc4a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>[lwc-15ihn5f4djl=&quot;&quot;] .slds-textarea</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@lwc-15ihn5f4djl = '']//*[@class and contains(concat(' ', normalize-space(@class), ' '), ' slds-textarea ')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;Description&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>textarea</value>
      <webElementGuid>7e892407-46d3-43ba-b2f8-f553209ec444</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>part</name>
      <type>Main</type>
      <value>textarea</value>
      <webElementGuid>95da5957-0d40-48b3-9316-d53339fa3ae0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>input-284</value>
      <webElementGuid>93beaa44-4adb-472e-9880-f6b437b5b3e8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>32000</value>
      <webElementGuid>2fa24ca2-f61f-43b4-8d7f-f6b86a792890</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>slds-textarea</value>
      <webElementGuid>a1e72e1b-b8ef-4383-9c6a-2c8799c9b39f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parent</name>
      <type>Main</type>
      <value>md5.v1-4dbcf98f0d015cc332fc86215605ac80</value>
      <webElementGuid>ff7d98ad-d42b-4bde-bd9e-9e5cd5d2a4fe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@lwc-15ihn5f4djl = '']//*[@class and contains(concat(' ', normalize-space(@class), ' '), ' slds-textarea ')]</value>
      <webElementGuid>89e30c05-3fbe-4b46-a6f6-877ab5ea9609</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//*[@lwc-15ihn5f4djl = '']//*[@class and contains(concat(' ', normalize-space(@class), ' '), ' slds-textarea ')]</value>
      <webElementGuid>1186b554-919a-48e3-afb3-e026efacc46a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//textarea[@id = 'input-284']</value>
      <webElementGuid>0a38df2a-1aa0-41d8-9f96-d783bcaac31e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
