<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Search this list</name>
   <tag></tag>
   <elementGuidId>69b5013c-a390-49e5-90f9-f23cb74f7580</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#input-67</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@aria-label='Search this list...']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:attr=[placeholder=&quot;Search this list...&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>d05f08ba-2c3c-488e-9558-ba21eb43aa58</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>slds-input</value>
      <webElementGuid>50dcd23c-9846-4f51-a0f6-40246967223c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>part</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>f4000b88-3944-45f1-9f7a-305f4acb13af</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Search this list...</value>
      <webElementGuid>ed206fd0-f5c7-449f-90e8-debef7dbe26e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>input-67</value>
      <webElementGuid>24af5803-120d-4c3a-9442-9dabf29f839e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>Contact-search-input</value>
      <webElementGuid>f622482b-8455-4bdb-9fdf-941207cf6b36</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Search this list...</value>
      <webElementGuid>ed980fb1-6c3c-4577-8fa0-0d40a86d7000</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>search</value>
      <webElementGuid>3d292f4a-f6e2-4ce7-8145-e0c8a93cfb71</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-describedby</name>
      <type>Main</type>
      <value>listviewSearchTooltip-52 help-message-67</value>
      <webElementGuid>00137825-c964-4b59-95e0-f5222b13baeb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-invalid</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>ccab56f7-e41e-44e3-b995-839a2c6ffcfd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;input-67&quot;)</value>
      <webElementGuid>d5bd4d8a-c848-43bb-be6a-e3e011d51d73</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='input-67']</value>
      <webElementGuid>91d9a87b-6d50-47ed-8020-d349e84e00a9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='brandBand_1']/div/div/div/div/div/div[2]/div[2]/force-list-view-manager-search-bar/div/lightning-input/lightning-primitive-input-simple/div/div/input</value>
      <webElementGuid>362ecebf-b7c6-42a1-b7f0-a0b07d06241f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//lightning-primitive-input-simple/div/div/input</value>
      <webElementGuid>99361ff1-7523-46a5-991f-623ad506877f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'input-67' and @name = 'Contact-search-input' and @placeholder = 'Search this list...' and @type = 'search']</value>
      <webElementGuid>dfc11812-dd78-4ee2-a29d-1be8373f12a0</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
